name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Configure Poetry environment
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install --no-interaction --no-ansi

      - name: Run tests
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          export PYTHONPATH=.
          poetry run pytest --maxfail=1 --disable-warnings -q